apiVersion: v1
kind: Secret
metadata:
  name: passsecret
  namespace: app-b
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxMC4xMC40LjEzNDo4MDgzIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IlBAc3N3MHJkIiwiYXV0aCI6IllXUnRhVzQ2VUVCemMzY3djbVE9In19fQ==

---
apiVersion: v1
kind: Service
metadata:
  name: app-b
  namespace: app-b
  labels:
    app: app-b
spec:
  selector:
    app: app-b
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: httpreq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b
  namespace: app-b
  labels:
    app: app-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-b
  template:
    metadata:
      labels:
        app: app-b
    spec:
      containers:
      - name: app-b
        image: 10.10.4.134:8083/repository/poc/app-b:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256Mi"
            cpu: "300m"
          requests:
            memory: "128Mi"
            cpu: "100m"
      imagePullSecrets:
      - name: passsecret
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: app-b-gateway
  namespace: app-b
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-b-virtual-service
  namespace: app-b
spec:
  hosts:
  - "*"
  gateways:
  - app-b-gateway
  http:
  - match:
    - uri:
        prefix: /app-b/
    - uri:
        exact: /app-b
    rewrite:
      uri: /
    route:
    - destination:
        host: app-b
        port:
          number: 80