apiVersion: v1
kind: Secret
metadata:
  name: passsecret
  namespace: app-a
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxMC4xMC40LjEzNDo4MDgzIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IlBAc3N3MHJkIiwiYXV0aCI6IllXUnRhVzQ2VUVCemMzY3djbVE9In19fQ==

---
apiVersion: v1
kind: Service
metadata:
  name: app-a
  namespace: app-a
  labels:
    app: app-a
spec:
  selector:
    app: app-a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: httpreq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
  namespace: app-a
  labels:
    app: app-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
      - name: app-a
        image: 10.10.4.134:8083/repository/poc/app-a:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
          - name: TRACING_B_URL
            value: http://app-b.app-b/
        resources:
          limits:
            memory: "256Mi"
            cpu: "300m"
          requests:
            memory: "128Mi"
            cpu: "100m"
      imagePullSecrets:
      - name: passsecret
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: app-a-gateway
  namespace: app-a
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-a-virtual-service
  namespace: app-a
spec:
  hosts:
  - "*"
  gateways:
  - app-a-gateway
  http:
  - match:
    - uri:
        prefix: /app-a/
    - uri:
        exact: /app-a
    rewrite:
      uri: /
    route:
    - destination:
        host: app-a
        port:
          number: 80